import Database from 'better-sqlite3';
import { EntityStore } from './entity-store.js';
import { SpatialGraph } from './spatial-graph.js';
import { getEntityHistory } from './events.js';
import { safeJsonParse } from '../utils/json-validator.js';

export function exportWorldModel(
  db: Database.Database,
  params: { project: string; format?: 'json' | 'geojson' | 'gltf' | 'obj' }
): any {
  const entities = EntityStore.listEntities(db, { project: params.project, limit: 10000 });
  const relations = SpatialGraph.getRelations(db, { project: params.project });
  const regions = db.prepare('SELECT * FROM regions WHERE project = ?').all(params.project);

  if (params.format === 'geojson') {
    return {
      type: 'FeatureCollection',
      features: entities
        .filter((e) => e.position)
        .map((e) => ({
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [e.position!.x, e.position!.y, e.position!.z],
          },
          properties: {
            id: e.id,
            name: e.name,
            type: e.type,
            status: e.status,
            confidence: e.confidence,
            tags: e.tags,
            ...e.properties,
          },
        })),
    };
  }

  if (params.format === 'gltf') {
    // Generate valid glTF 2.0 JSON representation
    const nodes: any[] = [];
    const entityNodes = entities
      .filter((e) => e.position)
      .map((e, idx) => {
        const node: any = {
          name: `${e.name} (${e.type})`,
          translation: [e.position!.x, e.position!.y, e.position!.z],
          scale: [
            e.bounding_box?.width || 1,
            e.bounding_box?.height || 1,
            e.bounding_box?.depth || 1,
          ],
          extras: {
            id: e.id,
            type: e.type,
            status: e.status,
            confidence: e.confidence,
            tags: e.tags,
          },
        };
        if (e.orientation) {
          node.extras.orientation = e.orientation;
        }
        nodes.push(node);
        return idx;
      });

    return {
      asset: {
        version: '2.0',
        generator: '@putervision/world-model-mcp',
      },
      scenes: [
        {
          name: `${params.project} Scene`,
          nodes: entityNodes,
        },
      ],
      scene: 0,
      nodes,
    };
  }

  if (params.format === 'obj') {
    // Generate Wavefront OBJ mesh
    let obj = `# Wavefront OBJ generated by @putervision/world-model-mcp\n# Project: ${params.project}\n\n`;
    let vertexOffset = 1;

    for (const e of entities) {
      if (!e.position) continue;
      const hw = (e.bounding_box?.width || 1) / 2;
      const hh = (e.bounding_box?.height || 1) / 2;
      const hd = (e.bounding_box?.depth || 1) / 2;
      const { x, y, z } = e.position;

      obj += `o ${e.name.replace(/\s+/g, '_')}_${e.id.slice(0, 8)}\n`;
      // 8 cube vertices
      obj += `v ${x - hw} ${y - hh} ${z - hd}\n`;
      obj += `v ${x + hw} ${y - hh} ${z - hd}\n`;
      obj += `v ${x + hw} ${y + hh} ${z - hd}\n`;
      obj += `v ${x - hw} ${y + hh} ${z - hd}\n`;
      obj += `v ${x - hw} ${y - hh} ${z + hd}\n`;
      obj += `v ${x + hw} ${y - hh} ${z + hd}\n`;
      obj += `v ${x + hw} ${y + hh} ${z + hd}\n`;
      obj += `v ${x - hw} ${y + hh} ${z + hd}\n`;

      // 6 faces (12 triangles)
      const vo = vertexOffset;
      obj += `f ${vo} ${vo + 1} ${vo + 2}\n`;
      obj += `f ${vo} ${vo + 2} ${vo + 3}\n`;
      obj += `f ${vo + 5} ${vo + 4} ${vo + 7}\n`;
      obj += `f ${vo + 5} ${vo + 7} ${vo + 6}\n`;
      obj += `f ${vo + 4} ${vo} ${vo + 3}\n`;
      obj += `f ${vo + 4} ${vo + 3} ${vo + 7}\n`;
      obj += `f ${vo + 1} ${vo + 5} ${vo + 6}\n`;
      obj += `f ${vo + 1} ${vo + 6} ${vo + 2}\n`;
      obj += `f ${vo + 3} ${vo + 2} ${vo + 6}\n`;
      obj += `f ${vo + 3} ${vo + 6} ${vo + 7}\n`;
      obj += `f ${vo + 4} ${vo + 5} ${vo + 1}\n`;
      obj += `f ${vo + 4} ${vo + 1} ${vo}\n\n`;

      vertexOffset += 8;
    }

    return obj;
  }

  return {
    project: params.project,
    version: '1.0.0',
    exported_at: new Date().toISOString(),
    entities,
    relations,
    regions,
  };
}

export function exportTrajectories(
  db: Database.Database,
  params: {
    project: string;
    format?: 'json' | 'joint' | 'spatial_vlm';
    trace_id?: string;
    limit?: number;
  }
): any {
  const limit = params.limit || 500;
  const rows = db
    .prepare(
      `
      SELECT h.*, e.name as entity_name, e.type as entity_type
      FROM entity_history h
      LEFT JOIN entities e ON h.entity_id = e.id
      WHERE h.project = ?
      ORDER BY h.rowid ASC
      LIMIT ?
    `
    )
    .all(params.project, limit) as any[];

  if (params.format === 'joint') {
    // Interleaved joint events correlating state-memory task_id, vision visual_state_id, and 3D pose
    return rows.map((r, idx) => ({
      step: idx + 1,
      timestamp: r.timestamp,
      trace_id: params.trace_id || r.task_id || `trace_${params.project}`,
      task_id: r.task_id || undefined,
      visual_state_id: r.visual_state_id || undefined,
      entity_id: r.entity_id,
      entity_name: r.entity_name,
      action: r.action,
      position: r.x !== null ? { x: r.x, y: r.y, z: r.z } : undefined,
      confidence: r.confidence ?? undefined,
      details: safeJsonParse(r.details_json || '{}', {}),
    }));
  }

  if (params.format === 'spatial_vlm') {
    // Multimodal instruction tuning format for Spatial-VLM / VLA models
    return rows
      .filter((r) => r.x !== null)
      .map((r) => ({
        id: r.id,
        timestamp: r.timestamp,
        instruction: `Predict the next 3D position and spatial state for entity "${r.entity_name || r.entity_id}" after action "${r.action}".`,
        response: `Position: (${r.x}, ${r.y}, ${r.z}), Confidence: ${r.confidence ?? 1.0}`,
        ground_truth: {
          position: { x: r.x, y: r.y, z: r.z },
          confidence: r.confidence,
          action: r.action,
          entity_type: r.entity_type,
        },
      }));
  }

  return rows.map((r, idx) => ({
    step: idx + 1,
    id: r.id,
    timestamp: r.timestamp,
    entity_id: r.entity_id,
    entity_name: r.entity_name,
    action: r.action,
    position: r.x !== null ? { x: r.x, y: r.y, z: r.z } : undefined,
    confidence: r.confidence ?? undefined,
    source: r.source,
    details: safeJsonParse(r.details_json || '{}', {}),
  }));
}
